const NOTIFICATION_TYPES = {
  SYSTEM: "SYSTEM",
  COMPLAINT: "COMPLAINT",
  APPROVAL: "APPROVAL",
  JOB_CARD: "JOB_CARD",
  MATERIAL: "MATERIAL",
  INVENTORY: "INVENTORY",
  HOSTEL: "HOSTEL",
  OVERDUE: "OVERDUE",
  HIGH_PRIORITY: "HIGH_PRIORITY",
  ANNOUNCEMENT: "ANNOUNCEMENT",
};

const PRIORITY_LEVELS = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
};

const SLA_HOURS = {
  LOW: 72,
  MEDIUM: 48,
  HIGH: 24,
  CRITICAL: 12,
};

module.exports = {
  NOTIFICATION_TYPES,
  PRIORITY_LEVELS,
  SLA_HOURS,
};
